import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const dist = resolve(import.meta.dirname, 'dist');

await mkdir(dist, { recursive: true });

const shared = {
  entryPoints: [resolve(import.meta.dirname, 'src/index.js')],
  bundle: true,
  platform: 'node',
  target: 'node18',
  // Externaliza TODAS las dependencias de node_modules (incluidas multer y sharp).
  // Cada dependencia se resuelve en runtime.
  packages: 'external',
  sourcemap: true,
};

await Promise.all([
  build({ ...shared, format: 'esm', outfile: resolve(dist, 'index.js') }),
  build({ ...shared, format: 'cjs', outfile: resolve(dist, 'index.cjs') }),
]);

await writeFile(
  resolve(dist, 'index.d.ts'),
  [
    'export interface GaleriaLogger {',
    '  info?: (...args: unknown[]) => void;',
    '  warn?: (...args: unknown[]) => void;',
    '  error?: (...args: unknown[]) => void;',
    '  debug?: (...args: unknown[]) => void;',
    '  log?: (...args: unknown[]) => void;',
    '}',
    'export interface GaleriaMiddlewares {',
    '  list?: any[];',
    '  read?: any[];',
    '  create?: any[];',
    '  update?: any[];',
    '  delete?: any[];',
    '}',
    'export interface GaleriaConfig {',
    '  uploadDir: string;',
    '  thumbnailsDir: string;',
    '  publicBaseUrl: string;',
    '  archivosPath: string;',
    '  maxFileSize: number;',
    '  allowedMimeTypes: string[];',
    '  thumbnailWidth: number;',
    '  defaultLimit: number;',
    '  maxLimit: number;',
    '}',
    'export interface CreateGaleriaImageOptions {',
    '  knex: any;',
    '  logger?: GaleriaLogger | ((...args: unknown[]) => void);',
    '  uploadDir?: string;',
    '  publicBaseUrl?: string;',
    '  archivosPath?: string;',
    '  maxFileSize?: number;',
    '  allowedMimeTypes?: string[];',
    '  thumbnailWidth?: number;',
    '  defaultLimit?: number;',
    '  maxLimit?: number;',
    '  middlewares?: GaleriaMiddlewares;',
    '  tabla?: string;',
    '  [key: string]: unknown;',
    '}',
    'export interface GaleriaImage {',
    '  id: number;',
    '  titulo: string | null;',
    '  descripcion: string | null;',
    '  seccion: string | null;',
    '  filename: string;',
    '  original_name: string | null;',
    '  mime_type: string;',
    '  size: number;',
    '  width: number | null;',
    '  height: number | null;',
    '  orden: number;',
    '  url: string;',
    '  thumbnail_url: string;',
    '  created_at?: string;',
    '  updated_at?: string;',
    '}',
    'export interface GaleriaListResult {',
    '  success: true;',
    '  data: GaleriaImage[];',
    '  total: number;',
    '  page: number;',
    '  limit: number;',
    '  pages: number;',
    '}',
    'export interface GaleriaImageAPI {',
    '  galeriaRouter: any;',
    '  config: GaleriaConfig;',
    '  rootPath: string;',
    '  list(query?: any): Promise<GaleriaListResult>;',
    '  getById(id: number | string): Promise<GaleriaImage | null>;',
    '  createFromFile(file: { path: string; originalname: string; mimetype: string; size: number }, meta?: Record<string, unknown>): Promise<GaleriaImage>;',
    '  update(id: number | string, changes: Record<string, unknown>): Promise<GaleriaImage | null>;',
    '  remove(id: number | string): Promise<boolean>;',
    '}',
    'export function resolveConfig(options?: Record<string, any>, env?: Record<string, string | undefined>): GaleriaConfig;',
    'export function normalizeLogger(logger?: any): GaleriaLogger;',
    'export function sanitizeFilename(name: string): string;',
    'export function buildFileUrl(config: GaleriaConfig, filename: string, thumbnail?: boolean): string;',
    'export function createGaleriaImage(options: CreateGaleriaImageOptions): GaleriaImageAPI;',
    'export default createGaleriaImage;',
    '',
  ].join('\n'),
  'utf8',
);

console.log('[build] dist generado (ESM + CJS + .d.ts)');
